### ISSUE TITLE
tooltips : Offline description not available 

### ISSUE THREAD

**Issue by alcaribou2** [de-jcup/eclipse-sql-editor#11]
Hello,

I'm trying to user sql editor in eclipse. 
When I click on an instruction, tolltip is displaid but only with a link to  wikipedia SQL and below it is written :" Offline description: not available".
?

**Comment by de-jcup** [comment]
Sorry for the late response - yes you are right. I got the same problem. Will be fixed.

**Comment by de-jcup** [comment]
Hm.. it's a bug and also a new feature... 
The tooltip folder is not included in the current release, but it contains currently only `select.html` ... so add also label enhancement...

**Comment by de-jcup** [comment]
Will use text from https://www.w3resource.com/sql/tutorials.php which has license:

> This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.

**Comment by de-jcup** [comment]
Now the offline tooltips are working and also have much details (see next example picture). The examples and description are adopted from https://www.w3resource.com/sql/tutorials.php - but because I do not know how long this website will be available, the online link still goes to english wikipedia entry about SQL syntax.

![image](https://user-images.githubusercontent.com/11644753/109089109-fd6ea100-7710-11eb-9f36-244b403d7b8e.png)
